name: Generate dashboard

on:
  workflow_dispatch:
  schedule:
    #- cron: '0 3 * * *'  # Kör varje natt kl 03:00 svensk tid

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python generate_dashboard.py

    - name: Copy dashboard.html to docs/
      run: |
        mkdir -p docs
        cp dashboard.html docs/dashboard.html

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add docs/dashboard.html
        git commit -m "Update dashboard [auto]" || echo "No changes to commit"
        git push
